/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class', // never toggled anywhere in this codebase -> site stays light-only
  content: ['./src/**/*.html', './src/**/*.js'],
  theme: {
    extend: {
      colors: {
        primary: '#421bcc',
        'on-secondary': '#ffffff',
        'outline-variant': '#c9c4d8',
        secondary: '#a33e1b',
        'translucent-card': 'rgba(255, 255, 255, 0.10)',
        'surface-variant': '#e2e0fc',
        'translucent-border': 'rgba(255, 255, 255, 0.25)',
        'on-error': '#ffffff',
        'primary-fixed': '#e5deff',
        'inverse-primary': '#c8bfff',
        'tertiary-container': '#835500',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#ffd197',
        'surface-dim': '#dad7f3',
        'secondary-container': '#ff825a',
        'secondary-fixed-dim': '#ffb59e',
        'error-container': '#ffdad6',
        background: '#fcf8ff',
        'surface-tint': '#F8F7FF',
        'tertiary-fixed': '#ffddb4',
        'on-secondary-container': '#711e00',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e8e5ff',
        'on-primary-fixed-variant': '#421acc',
        'inverse-surface': '#2f2e43',
        'surface-container-low': '#f5f2ff',
        'surface-container-highest': '#e2e0fc',
        tertiary: '#634000',
        'on-surface': '#1a1a2e',
        'secondary-fixed': '#ffdbd0',
        'primary-fixed-dim': '#c8bfff',
        'on-surface-variant': '#474555',
        'on-tertiary-fixed': '#291800',
        'surface-bright': '#fcf8ff',
        surface: '#fcf8ff',
        'inverse-on-surface': '#f2efff',
        'on-primary-container': '#dbd4ff',
        'on-tertiary-fixed-variant': '#633f00',
        'primary-container': '#5b3fe4',
        muted: '#555577',
        'on-error-container': '#93000a',
        'surface-canvas': '#FFFFFF',
        'border-subtle': '#E5E5F0',
        'on-secondary-fixed-variant': '#822704',
        'on-secondary-fixed': '#3a0b00',
        'brand-dark': '#3F2BA3',
        'on-primary-fixed': '#190064',
        'on-background': '#1a1a2e',
        'surface-container': '#efecff',
        outline: '#787587',
        'tertiary-fixed-dim': '#fdba5a',
        'brand-light': '#EDE9FD',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter-desktop': '24px',
        'space-96': '6rem',
        'space-2': '0.125rem',
        'space-40': '2.5rem',
        'space-8': '0.5rem',
        'margin-mobile': '24px',
        'space-16': '1rem',
        'space-64': '4rem',
        'margin-desktop': '32px',
        'space-20': '1.25rem',
        'space-120': '7.5rem',
        'space-12': '0.75rem',
        'space-4': '0.25rem',
        'space-32': '2rem',
        'space-24': '1.5rem',
        'gutter-mobile': '16px',
        'layout-max-width': '1200px',
        'space-48': '3rem',
      },
      maxWidth: {
        'layout-max-width': '1200px',
      },
      fontFamily: {
        'button-text': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-metric-mobile': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'display-hero': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-eyebrow': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'quote-text': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-large': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-metric': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'display-hero-mobile': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-base': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-small': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'button-text': ['15px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-metric-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-hero': ['60px', { lineHeight: '68px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-eyebrow': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'quote-text': ['19px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-large': ['17px', { lineHeight: '28px', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-metric': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-base': ['15px', { lineHeight: '24px', fontWeight: '500' }],
        'body-small': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};
